[package]
name = "frisbee"
version = "0.1.0"
authors = ["Anton Zhdan-Pushkin <maqquettex@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.1"

[dev-dependencies]
tempfile = "3"
