name:                frisbee
version:             0.1.0.0
github:              "maqquettex/frisbee"
license:             BSD3
author:              "Anton Zhdan-Pushkin"
maintainer:          "maqquettex@gmail.com"
copyright:           "2019 Anton Zhdan-Pushkin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/frisbee#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers
- hspec

library:
  source-dirs: src

executables:
  frisbee-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frisbee

tests:
  frisbee-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frisbee
